---
apiVersion: v1
kind: Secret
metadata:
  name: nexus3caac-secrets
  labels:
    app: nexus3caac
    nexus3caac: active
type: Opaque
data:
  nexus-secrets.yaml: |
    bmV4dXM6CiAgICBhZG1pblBhc3N3b3JkOiBteVN1cDNyUEBzc3cwcmQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus3caac-config
  labels:
    app: nexus3caac
    nexus3caac: active
data:
  nexus.yml: |
    nexus:
      anonymousAccessEnabled: false
    realms:
      - name: Docker Bearer Token Realm
        enabled: true
      - name: npm Bearer Token Realm
        enabled: true
    blobStores:
    - name: local
      type: file
      path: local
