apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus3caac-deployment
  labels:
    app: nexus3caac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3caac
  template:
    metadata:
      labels:
        app: nexus3caac
    spec:
      containers:
      - name: nexus3caac
        image: aamkye/nexus3caac-cli:latest
        args:
          - from-k8s
          - --namespace=nexus
          - --label=nexus3caac
          - --label-value=active
          - --resource=both
          - --watch
          - --refresh-period=3
        env:
          - name: NEXUS3_CAAC_LOG_LEVEL
            value: DEBUG
      serviceAccountName: {{ include "nexuscaac.serviceAccountName" . }}

