---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nexus3caac-configmap-secret-reader-role
  namespace: {{ .Values.namespace }}
  labels:
    app: nexus3caac
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
