apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-configmaps-secrets
subjects:
  - kind: ServiceAccount
    name: {{ include "nexuscaac.serviceAccountName" . }}
roleRef:
  kind: Role
  name: configmap-secret-reader
  apiGroup: rbac.authorization.k8s.io
