apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: nexus
  name: configmap-secret-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]