---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nexuscaac.serviceAccountName" . }}
  labels: {{- include "nexuscaac.labels" . | nindent 4 }}
  {{- if .Values.nexuscaac.extraLabels }}
    {{- with .Values.nexuscaac.extraLabels }}
      {{ toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
