---
apiVersion: v1
kind: Secret
metadata:
  name: nexus3caac-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app: nexus3caac
    nexus3caac: active
type: Opaque
data:
  {{- with .Values.configSecrets }}
  nexus-secrets.yaml: {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus3caac-config
  namespace: {{ .Values.namespace }}
  labels:
    app: nexus3caac
    nexus3caac: active
data:
  {{- with .Values.config }}
  nexus.yml: {{- toYaml . | nindent 4 }}
  {{- end }}
