---
apiVersion: v1
kind: Secret
metadata:
  name: nexus3caac-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app: nexus3caac
    nexus3caac: active
type: Opaque
data:
  nexus-yaml: |
{{- toYaml .Values.configSecrets | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus3caac-config
  namespace: {{ .Values.namespace }}
  labels:
    app: nexus3caac
    nexus3caac: active
data:
  nexus-yaml: |
{{- toYaml .Values.config | nindent 4 }}
