---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus3caac-deployment
  labels:
    app: nexus3caac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3caac
  template:
    metadata:
      labels:
        app: nexus3caac
    spec:
      containers:
        - name: nexus3caac-watcher
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - from-k8s
            - --namespace={{ .Values.namespace }}
            - --label=nexus3caac
            - --label-value=active
            - --resource=both
            - --watch
            - --refresh-period={{ .Values.refreshPeriod }}
          env:
            - name: NEXUS3_CAAC_LOG_LEVEL
              value: DEBUG
      serviceAccountName: {{ .Values.serviceAccountName }}

