---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nexus3caac-read-configmaps-rbac
  labels:
    app: nexus3caac
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
roleRef:
  kind: Role
  name: nexus3caac-configmap-reader-role
  apiGroup: rbac.authorization.k8s.io
