---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nexus3caac-configmap-reader-role
  labels:
    app: nexus3caac
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
