######
# helm repo add nexus3-caac https://aamkye.github.io/nexus3-caac-cli/
# helm repo update
# helm upgrade --install nexus3-caac/nexus-config-as-a-code-cli -f helm-values/nexus-caac.yml nexus3-caac
# helm uninstall nexus3-caac
######

configSecrets:
  nexus:
    adminPassword: "admin1234"

config:
  nexus:
    baseUrl: http://localhost:8081
    anonymousAccessEnabled: false
    defaults:
      adminUser: admin
      adminPassword: admin123
    deleteUnknownItems:
      blobstores: false
      contentSelectors: false
      cleanupPolicies: false
      routingRules: false
      repos: false
      ldapConnections: false
      customLocalUsers: false
      customRoles: false
      customPrivileges: false
      tasks: false
  realms: []
  httpClient: {}
  blobStores: []
  cleanupPolicies: []
  routingRules: []
  contentSelectors: []
  repositories: []
  smtpConnection:
    enabled: false
  ldapConnections: []
  customUsers:
    local: []
    ldap: []
  customRoles: []
  customPrivileges: []
  certificates: []
  tasks: []

image:
  repository: aamkye/nexus3caac-cli
  tag: latest
  pullPolicy: IfNotPresent
namespace: nexus
serviceAccountName: nexus3caac
