name: Docker CI
on:
  push:
    tags:
      - '*'

jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO_NAME}}:${{ github.ref_name }}
        docker tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO_NAME}}:${{ github.ref_name }} ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO_NAME}}:latest

    - name: Docker Push
      run: |
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO_NAME}}:${{ github.ref_name }}
        docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_REPO_NAME}}:latest
