
name: HELM RELEASE

on:
  push:
    tags:
      - '*'
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Run chart-releaser
        uses: askcloudarchitech/chart-releaser-action@skip-packaging-option
        env:
          CR_TOKEN: '${{ secrets.CR_TOKEN }}'
