name: HELM CI - Lint

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - uses: helm/chart-testing-action@main

      - name: Run chart-testing (list-changed)
        run: ct list-changed --target-branch ${{ github.event.repository.default_branch }}

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run helm-docs
        run: .github/helm-docs.sh

  kubeconform-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          - 1.25.2
          - 1.25.0
          - 1.24.6
          - 1.24.4
          - 1.23.12
          - 1.23.10
          - 1.22.15
          - 1.22.13
          - 1.21.14
          - 1.20.15
          - 1.19.16
          - 1.18.20
          - 1.17.17
          - 1.16.15
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run kubeconform
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeconform.sh

  kube-score-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run kube-score
        run: .github/kube-score.sh || exit 0 #To avoid failing the build

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
      - kube-score-chart
      - kubeconform-chart
    strategy:
      matrix:
        k8s:
          - 1.25.2
          - 1.25.0
          - 1.24.6
          - 1.24.4
          - 1.23.12
          - 1.23.10
          - 1.22.15
          - 1.22.13
          - 1.21.14
          - 1.20.15
          - 1.19.16
          - 1.18.20
          - 1.17.17
          - 1.16.15
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: helm/kind-action@main
        with:
          node_image: kindest/node:${{ matrix.k8s }}

      - uses: helm/chart-testing-action@main

      - name: Run chart-testing (install)
        run: ct install
