name: HELM CI - Lint

on:
  push:
    tags:
      - "*"
    branches:
      - master
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - uses: helm/chart-testing-action@main

      - name: Run chart-testing (list-changed)
        run: ct list-changed --target-branch ${{ github.event.repository.default_branch }}

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run helm-docs
        run: .github/helm-docs.sh

  kubeconform-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-docs
    strategy:
      matrix:
        k8s:
          - 1.25.2
          - 1.25.0
          - 1.24.6
          - 1.24.4
          - 1.23.12
          - 1.23.10
          - 1.22.15
          - 1.22.13
          - 1.21.14
          - 1.20.15
          - 1.19.16
          - 1.18.20
          - 1.17.17
          - 1.16.15
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run kubeconform
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeconform.sh

  kube-score-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-docs
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run kube-score
        run: .github/kube-score.sh || exit 0 #To avoid failing the build

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - kube-score-chart
      - kubeconform-chart
    strategy:
      matrix:
        k8s:
          - 1.25.2
          - 1.25.0
          - 1.24.6
          - 1.24.4
          - 1.23.12
          - 1.23.10
          - 1.22.15
          - 1.22.13
          - 1.21.14
          - 1.20.15
          - 1.19.16
          - 1.18.20
          - 1.17.17
          - 1.16.15
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: helm/kind-action@main
        with:
          node_image: kindest/node:v${{ matrix.k8s }}

      - uses: helm/chart-testing-action@main

      - name: Run chart-testing (install)
        run: ct install

  release:
    if: startsWith(github.ref, 'refs/tags/') && github.event_name != 'pull_request'
    name: release-charts
    needs:
      - install-chart
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: custom packaging
        run: |
          VERSION=${{github.ref_name}}
          rm -rf .cr-release-packages
          mkdir -p .cr-release-packages
          helm package charts --app-version=${VERSION:1} --version=${VERSION:1} --destination=.cr-release-packages

      - name: Run chart-releaser
        # switch back to helm/chart-releaser-action if this contribution is ever merged
        uses: askcloudarchitech/chart-releaser-action@skip-packaging-option
        with:
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
